env:
  es6: true
  browser: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
settings:
  react:
    pragma: React
    version: 15.0.2
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - off
  # no-undef:
  #   - off
